### ISSUE TITLE
Integrate AWS EFS

### ISSUE THREAD

**Issue by AlexNeff** [upsidetravel/bucket-antivirus-function#168]
If it's possible to store files from an EFS file store, the current file size limit could be removed.

**Comment by jdepp** [comment]
This could be implemented but may involve quite a bit. Just thinking out loud here: you'd have to setup some kind of workflow with AWS DataSync, SNS, and EFS to transfer large S3 objects to EFS so that Lambda can access it via EFS. The Bucket AV scanner function would also need a new trigger of type SNS (for when S3 uses DataSync to get the large object into EFS, and then trigger an SNS notification saying it did so) so that the scanner function knows to grab the file from EFS instead of S3, and then update the tagging on the S3 object. I think it's a good idea, and we'd welcome a PR or some kind of POC on this!

**Comment by AlexNeff** [comment]
I appreciate the quick replies, we may end up doing that route, if we do you'll see it here!

**Comment by jdepp** [comment]
Awesome, I'm going to close this ticket but feel free to open another Issue or PR if/when you decide to go that route!
